title: Jay Thanki
logo: /assets/img/headshot_circle.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate Data Scientist with a strong foundation in Computer Science Engineering and a Master's degree in Data Science from University at Buffalo.
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
