title: Jay Thanki
logo: /assets/img/headshot_circle.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Science Enthusiast with a background in Computer Science Engineering and a master's degree in Data Science from University at Buffalo.
  <br><br>
theme: jekyll-theme-minimal
